---
name: Swan9.nl
description: Something
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: henk.van.den.brink@gmail.com
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  hvdb:
    name: Henk
    site: https://www.swan9.nl
    avatar: "/assets/images/avatar1.jpg"
    bio: Hello!
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
