# This is a basic workflow to help you get started with Actions

name: Deploy to remote

on:
  push:
    branches: [ gh-pages ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: src/
        remote_path: /home/henk/public_html
        remote_host: swan9.nl
        remote_port: 7685
        remote_user: henk
        remote_key: ${{ secrets.DEPLOY_KEY }}
